/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "tertiary": "#006242",
        "on-secondary-container": "#fffbff",
        "surface-container-high": "#dce9ff",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "on-tertiary-container": "#bdffdb",
        "tertiary-fixed": "#6ffbbe",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed": "#00174b",
        "on-primary-container": "#eeefff",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed": "#eaddff",
        "on-secondary-fixed": "#25005a",
        "tertiary-container": "#007d55",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#d2bbff",
        "secondary": "#712ae2",
        "on-surface-variant": "#434655",
        "surface": "#f8f9ff",
        "on-secondary-fixed-variant": "#5a00c6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-tint": "#0053db",
        "on-tertiary-fixed": "#002113",
        "primary": "#004ac6",
        "outline-variant": "#c3c6d7",
        "secondary-container": "#8a4cfc",
        "inverse-surface": "#213145",
        "primary-container": "#2563eb",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#737686",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#003ea8",
        "on-surface": "#0b1c30",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "unit": "4px",
        "container-max": "1440px",
        "section-gap": "80px"
      },
      fontFamily: {
        "stats-number": ["Manrope", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "display-hero": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "stats-number": ["36px", { "lineHeight": "44px", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "display-hero": ["72px", { "lineHeight": "84px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
